// Accurate engine: turn the engine-neutral AirflowCase into a complete
// OpenFOAM case (buoyantSimpleFoam, steady buoyant indoor air).
//
// The output is a flat map of { relativePath: fileContents }. The local
// backend writes these verbatim to a run directory and executes ./Allrun.
//
// Design choices (kept deliberately conventional so a stock OpenFOAM.com /
// ESI build runs it):
//   - Room  -> blockMesh hex box with six named wall patches.
//   - AC    -> a real velocity+temperature inlet patch carved from the rear
//              wall with topoSet + createPatch (the dominant, well-posed BC).
//   - Vent  -> a pressure outlet patch carved from the rear wall.
//   - Fan   -> an fvOptions momentum (jet) source in a sphere cellZone.
//   - Heat  -> fvOptions energy sources for warm bodies / lamp (buoyancy).
//   - Furniture -> ASCII STL boxes refined in by snappyHexMesh.
//
// This is a faithful starting case. Because it is generated without a live
// OpenFOAM to validate against, the backend reports the real solver log so
// first-run tuning (mesh counts, relaxation) is visible to the user.

import type { AirflowCase, BoxObstacle } from '../airflowCase.ts'

export interface OpenFoamCase {
  name: string
  /** relativePath -> file contents. */
  files: Record<string, string>
  /** Names of the carved inlet/outlet patches, for reference. */
  patches: { inlets: string[]; outlets: string[] }
}

const FOAM_HEADER = (cls: string, object: string, location?: string) =>
  `/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: generated by interactive_airflow      |
|  \\\\    /   O peration     |                                                 |
|   \\\\  /    A nd           | Accurate engine case export                     |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       ${cls};${location ? `\n    location    "${location}";` : ''}
    object      ${object};
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
`

const vec = (v: [number, number, number]) => `(${v[0]} ${v[1]} ${v[2]})`

export function exportOpenFoamCase(c: AirflowCase): OpenFoamCase {
  const files: Record<string, string> = {}
  const inletNames = c.inlets.map((i) => `${i.id}Inlet`)
  const outletNames = c.outlets.map((o) => `${o.id}Outlet`)

  files['system/controlDict'] = controlDict()
  files['system/fvSchemes'] = fvSchemes()
  files['system/fvSolution'] = fvSolution()
  files['system/blockMeshDict'] = blockMeshDict(c)
  files['system/topoSetDict'] = topoSetDict(c)
  files['system/createPatchDict'] = createPatchDict(c)
  files['system/fvOptions'] = fvOptions(c)
  files['system/sampleGrid'] = sampleGridDict(c)

  files['constant/g'] = gFile()
  files['constant/thermophysicalProperties'] = thermophysicalProperties(c)
  files['constant/turbulenceProperties'] = turbulenceProperties()

  files['0/U'] = fieldU(c, inletNames, outletNames)
  files['0/T'] = fieldT(c, inletNames, outletNames)
  files['0/p_rgh'] = fieldPrgh(inletNames, outletNames)
  files['0/p'] = fieldP(inletNames, outletNames)

  // Furniture obstacles as STL surfaces + snappyHexMesh setup.
  if (c.obstacles.length > 0) {
    files['system/snappyHexMeshDict'] = snappyHexMeshDict(c)
    files['system/meshQualityDict'] = meshQualityDict()
    for (const o of c.obstacles) {
      files[`constant/triSurface/${o.id}.stl`] = boxStl(o)
    }
  }

  files['Allrun'] = allrun(c)
  files['Allclean'] = allclean()
  files['case.json'] = JSON.stringify(c, null, 2)
  files['README.md'] = caseReadme(c, inletNames, outletNames)

  return { name: c.name, files, patches: { inlets: inletNames, outlets: outletNames } }
}

// ---------------------------------------------------------------------------
// system/
// ---------------------------------------------------------------------------

function controlDict(): string {
  return (
    FOAM_HEADER('dictionary', 'controlDict', 'system') +
    `
application     buoyantSimpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         1000;
deltaT          1;
writeControl    timeStep;
writeInterval   100;
purgeWrite      2;
writeFormat     ascii;
writePrecision  7;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;
`
  )
}

function fvSchemes(): string {
  return (
    FOAM_HEADER('dictionary', 'fvSchemes', 'system') +
    `
ddtSchemes      { default steadyState; }
gradSchemes     { default Gauss linear; }
divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss upwind;
    div(phi,h)      bounded Gauss upwind;
    div(phi,K)      bounded Gauss upwind;
    div(phi,epsilon) bounded Gauss upwind;
    div(phi,k)      bounded Gauss upwind;
    div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes   { default corrected; }
`
  )
}

function fvSolution(): string {
  return (
    FOAM_HEADER('dictionary', 'fvSolution', 'system') +
    `
solvers
{
    p_rgh
    {
        solver          GAMG;
        smoother        DICGaussSeidel;
        tolerance       1e-7;
        relTol          0.01;
    }
    "(U|h|k|epsilon)"
    {
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-7;
        relTol          0.1;
    }
}

SIMPLE
{
    momentumPredictor yes;
    nNonOrthogonalCorrectors 0;
    pRefCell        0;
    pRefValue       0;
    residualControl
    {
        p_rgh           1e-3;
        U               1e-3;
        h               1e-3;
    }
}

relaxationFactors
{
    fields  { rho 1.0; p_rgh 0.7; }
    equations { U 0.3; h 0.3; "(k|epsilon)" 0.5; }
}
`
  )
}

function blockMeshDict(c: AirflowCase): string {
  const { width: W, height: H, depth: D } = c.room
  const x0 = -W / 2
  const x1 = W / 2
  const z0 = -D / 2
  const z1 = D / 2
  // ~0.15 m cells -> a reasonable, fast indoor mesh before snappy refinement.
  const nx = Math.max(20, Math.round(W / 0.15))
  const ny = Math.max(12, Math.round(H / 0.15))
  const nz = Math.max(16, Math.round(D / 0.15))
  return (
    FOAM_HEADER('dictionary', 'blockMeshDict', 'system') +
    `
scale   1;

vertices
(
    (${x0} 0 ${z0})
    (${x1} 0 ${z0})
    (${x1} ${H} ${z0})
    (${x0} ${H} ${z0})
    (${x0} 0 ${z1})
    (${x1} 0 ${z1})
    (${x1} ${H} ${z1})
    (${x0} ${H} ${z1})
);

blocks
(
    hex (0 1 5 4 3 2 6 7) (${nx} ${nz} ${ny}) simpleGrading (1 1 1)
);

edges ();

boundary
(
    floor      { type wall; faces ( (0 1 5 4) ); }
    ceiling    { type wall; faces ( (3 7 6 2) ); }
    backWall   { type wall; faces ( (0 3 2 1) ); }
    frontWall  { type wall; faces ( (4 5 6 7) ); }
    leftWall   { type wall; faces ( (0 4 7 3) ); }
    rightWall  { type wall; faces ( (1 2 6 5) ); }
);

mergePatchPairs ();
`
  )
}

// Carve inlet/outlet face sets out of the rear (back) wall using axis-aligned
// boxes around each device, then createPatch promotes them to real patches.
function topoSetDict(c: AirflowCase): string {
  const actions: string[] = []
  const faceBox = (id: string, center: [number, number, number], size: [number, number]) => {
    const [cx, cy, cz] = center
    const [sw, sh] = size
    const min = vec([cx - sw / 2 - 0.05, cy - sh / 2 - 0.05, cz - 0.2])
    const max = vec([cx + sw / 2 + 0.05, cy + sh / 2 + 0.05, cz + 0.2])
    return `    {
        name    ${id}FaceSet;
        type    faceSet;
        action  new;
        source  boxToFace;
        sourceInfo { box ${min} ${max}; }
    }
    {
        name    ${id}FaceSet;
        type    faceSet;
        action  subset;
        source  patchToFace;
        sourceInfo { patch backWall; }
    }`
  }
  for (const i of c.inlets) actions.push(faceBox(`${i.id}Inlet`, i.center, i.size))
  for (const o of c.outlets) actions.push(faceBox(`${o.id}Outlet`, o.center, o.size))

  // Fan jet as a sphere cellZone for fvOptions.
  for (const f of c.fans) {
    actions.push(`    {
        name    ${f.id}Zone;
        type    cellZoneSet;
        action  new;
        source  sphereToCell;
        sourceInfo { centre ${vec(f.center)}; radius ${f.radius}; }
    }`)
  }
  // Heat sources as sphere cellZones for fvOptions.
  for (const h of c.heat) {
    actions.push(`    {
        name    ${h.id}Zone;
        type    cellZoneSet;
        action  new;
        source  sphereToCell;
        sourceInfo { centre ${vec(h.center)}; radius ${h.radius}; }
    }`)
  }

  return (
    FOAM_HEADER('dictionary', 'topoSetDict', 'system') +
    `
actions
(
${actions.join('\n')}
);
`
  )
}

function createPatchDict(c: AirflowCase): string {
  const patch = (name: string, set: string, type: string) => `    {
        name ${name};
        patchInfo { type ${type}; }
        constructFrom set;
        set ${set};
    }`
  const patches: string[] = []
  for (const i of c.inlets) patches.push(patch(`${i.id}Inlet`, `${i.id}InletFaceSet`, 'patch'))
  for (const o of c.outlets) patches.push(patch(`${o.id}Outlet`, `${o.id}OutletFaceSet`, 'patch'))
  return (
    FOAM_HEADER('dictionary', 'createPatchDict', 'system') +
    `
pointSync false;

patches
(
${patches.join('\n')}
);
`
  )
}

// Fan momentum + heat energy as fvOptions cell-zone sources.
function fvOptions(c: AirflowCase): string {
  const blocks: string[] = []
  for (const f of c.fans) {
    // Approximate jet acceleration: reach target speed over ~0.3 s of residence.
    const accel = f.speed / 0.3
    const a: [number, number, number] = [
      f.direction[0] * accel,
      f.direction[1] * accel,
      f.direction[2] * accel,
    ]
    blocks.push(`${f.id}Source
{
    type            semiImplicitSource;
    selectionMode   cellZone;
    cellZone        ${f.id}Zone;
    volumeMode      specific;
    injectionRateSuSp
    {
        U  (${vec(a)} 0);
    }
}`)
  }
  for (const h of c.heat) {
    // Heat as an enthalpy source. Map a few K of warmth to ~W/m^3 (heuristic).
    const power = Math.max(0, h.deltaT) * 120
    blocks.push(`${h.id}Source
{
    type            semiImplicitSource;
    selectionMode   cellZone;
    cellZone        ${h.id}Zone;
    volumeMode      specific;
    injectionRateSuSp
    {
        h  (${power} 0);
    }
}`)
  }
  return FOAM_HEADER('dictionary', 'fvOptions', 'system') + '\n' + blocks.join('\n\n') + '\n'
}

// Structured sample grid the backend reads back to the web viewer.
function sampleGridDict(c: AirflowCase): string {
  const { width: W, height: H, depth: D } = c.room
  const nx = 32
  const ny = 14
  const nz = 24
  return (
    FOAM_HEADER('dictionary', 'sampleGrid', 'system') +
    `
// Used via: postProcess -func sampleGrid
type            surfaces;
libs            ("libsampling.so");

// A uniform internal grid sampled into VTK; the backend converts it to the
// web viewer's velocity volume. nx=${nx} ny=${ny} nz=${nz} over the room.
interpolationScheme cellPoint;
setFormat       raw;
fields          ( U T );

sets
(
    grid
    {
        type    cloud;
        axis    xyz;
        points  GRID_POINTS_PLACEHOLDER;
    }
);

// Room extent: x[${-W / 2}, ${W / 2}] y[0, ${H}] z[${-D / 2}, ${D / 2}]
`
  )
}

// ---------------------------------------------------------------------------
// constant/
// ---------------------------------------------------------------------------

function gFile(): string {
  return (
    FOAM_HEADER('uniformDimensionedVectorField', 'g', 'constant') +
    `
dimensions      [0 1 -2 0 0 0 0];
value           (0 -9.81 0);
`
  )
}

function thermophysicalProperties(c: AirflowCase): string {
  return (
    FOAM_HEADER('dictionary', 'thermophysicalProperties', 'constant') +
    `
thermoType
{
    type            heRhoThermo;
    mixture         pureMixture;
    transport       const;
    thermo          hConst;
    equationOfState perfectGas;
    specie          specie;
    energy          sensibleEnthalpy;
}

mixture
{
    specie      { molWeight 28.96; }
    thermodynamics { Cp 1005; Hf 0; }
    transport   { mu 1.8e-5; Pr 0.7; }
}

// Ambient reference: ${c.ambientTemperature} K
`
  )
}

function turbulenceProperties(): string {
  return (
    FOAM_HEADER('dictionary', 'turbulenceProperties', 'constant') +
    `
simulationType  laminar;
`
  )
}

// ---------------------------------------------------------------------------
// 0/
// ---------------------------------------------------------------------------

function wallEntries(patches: string[], body: string): string {
  return patches.map((p) => `    ${p}\n    {\n${body}\n    }`).join('\n')
}

function fieldU(c: AirflowCase, inlets: string[], outlets: string[]): string {
  const inletBlocks = c.inlets
    .map((i, idx) => {
      const u: [number, number, number] = [
        i.normal[0] * i.speed,
        i.normal[1] * i.speed,
        i.normal[2] * i.speed,
      ]
      return `    ${inlets[idx]}
    {
        type            fixedValue;
        value           uniform ${vec(u)};
    }`
    })
    .join('\n')
  const outletBlocks = wallEntries(
    outlets,
    `        type            pressureInletOutletVelocity;\n        value           uniform (0 0 0);`,
  )
  return (
    FOAM_HEADER('volVectorField', 'U', '0') +
    `
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform (0 0 0);

boundaryField
{
    "(floor|ceiling|backWall|frontWall|leftWall|rightWall)"
    {
        type            noSlip;
    }
${inletBlocks}
${outletBlocks}
}
`
  )
}

function fieldT(c: AirflowCase, inlets: string[], outlets: string[]): string {
  const inletBlocks = c.inlets
    .map(
      (i, idx) => `    ${inlets[idx]}
    {
        type            fixedValue;
        value           uniform ${i.temperature};
    }`,
    )
    .join('\n')
  const outletBlocks = wallEntries(outlets, `        type            inletOutlet;\n        inletValue      uniform ${c.ambientTemperature};\n        value           uniform ${c.ambientTemperature};`)
  return (
    FOAM_HEADER('volScalarField', 'T', '0') +
    `
dimensions      [0 0 0 1 0 0 0];
internalField   uniform ${c.ambientTemperature};

boundaryField
{
    "(floor|ceiling|backWall|frontWall|leftWall|rightWall)"
    {
        type            zeroGradient;
    }
${inletBlocks}
${outletBlocks}
}
`
  )
}

function fieldPrgh(inlets: string[], outlets: string[]): string {
  const inletBlocks = wallEntries(inlets, `        type            fixedFluxPressure;\n        value           uniform 0;`)
  const outletBlocks = wallEntries(outlets, `        type            prghPressure;\n        p               uniform 0;\n        value           uniform 0;`)
  return (
    FOAM_HEADER('volScalarField', 'p_rgh', '0') +
    `
dimensions      [1 -1 -2 0 0 0 0];
internalField   uniform 0;

boundaryField
{
    "(floor|ceiling|backWall|frontWall|leftWall|rightWall)"
    {
        type            fixedFluxPressure;
        value           uniform 0;
    }
${inletBlocks}
${outletBlocks}
}
`
  )
}

function fieldP(inlets: string[], outlets: string[]): string {
  const all = [...inlets, ...outlets]
  const extra = all.length
    ? '\n' + wallEntries(all, `        type            calculated;\n        value           uniform 1e5;`)
    : ''
  return (
    FOAM_HEADER('volScalarField', 'p', '0') +
    `
dimensions      [1 -1 -2 0 0 0 0];
internalField   uniform 1e5;

boundaryField
{
    "(floor|ceiling|backWall|frontWall|leftWall|rightWall)"
    {
        type            calculated;
        value           uniform 1e5;
    }${extra}
}
`
  )
}

// ---------------------------------------------------------------------------
// snappyHexMesh + STL obstacles
// ---------------------------------------------------------------------------

function snappyHexMeshDict(c: AirflowCase): string {
  const geometry = c.obstacles
    .map((o) => `    ${o.id}.stl { type triSurfaceMesh; name ${o.id}; }`)
    .join('\n')
  const refinement = c.obstacles
    .map((o) => `        ${o.id} { level (1 1); }`)
    .join('\n')
  // A point guaranteed to be inside the room air (near ceiling centre, away
  // from furniture which sits low).
  const insidePoint = vec([0, c.room.height - 0.3, 0])
  return (
    FOAM_HEADER('dictionary', 'snappyHexMeshDict', 'system') +
    `
castellatedMesh true;
snap            true;
addLayers       false;

geometry
{
${geometry}
}

castellatedMeshControls
{
    maxLocalCells 1000000;
    maxGlobalCells 4000000;
    minRefinementCells 10;
    nCellsBetweenLevels 2;
    features ();
    refinementSurfaces
    {
${refinement}
    }
    resolveFeatureAngle 30;
    refinementRegions {}
    locationInMesh ${insidePoint};
    allowFreeStandingZoneFaces true;
}

snapControls
{
    nSmoothPatch 3;
    tolerance 2.0;
    nSolveIter 30;
    nRelaxIter 5;
}

addLayersControls
{
    relativeSizes true;
    layers {}
    expansionRatio 1.0;
    finalLayerThickness 0.3;
    minThickness 0.1;
    nGrow 0;
    featureAngle 60;
    nRelaxIter 3;
    nSmoothSurfaceNormals 1;
    nSmoothNormals 3;
    nSmoothThickness 10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle 90;
    nBufferCellsNoExtrude 0;
    nLayerIter 50;
}

meshQualityControls
{
    #include "meshQualityDict"
}

writeFlags ( scalarLevels layerSets layerFields );
mergeTolerance 1e-6;
`
  )
}

function meshQualityDict(): string {
  return (
    FOAM_HEADER('dictionary', 'meshQualityDict', 'system') +
    `
maxNonOrtho 65;
maxBoundarySkewness 20;
maxInternalSkewness 4;
maxConcave 80;
minVol 1e-13;
minTetQuality 1e-15;
minArea -1;
minTwist 0.02;
minDeterminant 0.001;
minFaceWeight 0.05;
minVolRatio 0.01;
minTriangleTwist -1;
nSmoothScale 4;
errorReduction 0.75;
`
  )
}

// One axis-aligned (yaw-rotated) box as an ASCII STL solid.
function boxStl(o: BoxObstacle): string {
  const hw = o.w / 2
  const hd = o.d / 2
  const cos = Math.cos(o.yaw)
  const sin = Math.sin(o.yaw)
  // 8 corners (yaw about Y), y from 0..h.
  const corner = (sx: number, sz: number, y: number): [number, number, number] => {
    const lx = sx * hw
    const lz = sz * hd
    return [o.cx + lx * cos - lz * sin, y, o.cz + lx * sin + lz * cos]
  }
  const v = [
    corner(-1, -1, 0),
    corner(1, -1, 0),
    corner(1, 1, 0),
    corner(-1, 1, 0),
    corner(-1, -1, o.h),
    corner(1, -1, o.h),
    corner(1, 1, o.h),
    corner(-1, 1, o.h),
  ]
  // 12 triangles (2 per face), outward winding.
  const faces: Array<[number, number, number]> = [
    [0, 2, 1], [0, 3, 2], // bottom
    [4, 5, 6], [4, 6, 7], // top
    [0, 1, 5], [0, 5, 4], // -z
    [2, 3, 7], [2, 7, 6], // +z
    [1, 2, 6], [1, 6, 5], // +x
    [3, 0, 4], [3, 4, 7], // -x
  ]
  const tri = (a: number, b: number, c: number) => {
    const n = normal(v[a], v[b], v[c])
    return `  facet normal ${n[0]} ${n[1]} ${n[2]}
    outer loop
      vertex ${v[a].join(' ')}
      vertex ${v[b].join(' ')}
      vertex ${v[c].join(' ')}
    endloop
  endfacet`
  }
  return `solid ${o.id}\n${faces.map((f) => tri(f[0], f[1], f[2])).join('\n')}\nendsolid ${o.id}\n`
}

function normal(
  a: [number, number, number],
  b: [number, number, number],
  c: [number, number, number],
): [number, number, number] {
  const u = [b[0] - a[0], b[1] - a[1], b[2] - a[2]]
  const w = [c[0] - a[0], c[1] - a[1], c[2] - a[2]]
  const n: [number, number, number] = [
    u[1] * w[2] - u[2] * w[1],
    u[2] * w[0] - u[0] * w[2],
    u[0] * w[1] - u[1] * w[0],
  ]
  const len = Math.hypot(n[0], n[1], n[2]) || 1
  return [n[0] / len, n[1] / len, n[2] / len]
}

// ---------------------------------------------------------------------------
// scripts
// ---------------------------------------------------------------------------

function allrun(c: AirflowCase): string {
  const snappy = c.obstacles.length > 0 ? 'runApplication snappyHexMesh -overwrite\n' : ''
  return `#!/bin/sh
cd "\${0%/*}" || exit 1
. "\${WM_PROJECT_DIR:?}/bin/tools/RunFunctions"

runApplication blockMesh
${snappy}runApplication topoSet
runApplication createPatch -overwrite
runApplication buoyantSimpleFoam

# The backend samples the final time directly; this is a convenience hook.
echo "Done. Latest time:" && foamListTimes -latestTime
`
}

function allclean(): string {
  return `#!/bin/sh
cd "\${0%/*}" || exit 1
. "\${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions"
cleanCase
rm -rf constant/polyMesh/sets
`
}

function caseReadme(c: AirflowCase, inlets: string[], outlets: string[]): string {
  return `# OpenFOAM case: ${c.name}

Generated by the interactive_airflow accurate engine (buoyantSimpleFoam, laminar).

- Room: ${c.room.width} x ${c.room.depth} x ${c.room.height} m (W x D x H)
- Inlets: ${inlets.join(', ') || 'none'}
- Outlets: ${outlets.join(', ') || 'none'}
- Fans (fvOptions momentum): ${c.fans.length}
- Heat sources (fvOptions energy): ${c.heat.length}
- Obstacles (snappyHexMesh STL): ${c.obstacles.length}

## Run

\`\`\`sh
./Allrun        # blockMesh -> snappyHexMesh -> topoSet -> createPatch -> buoyantSimpleFoam
\`\`\`

Requires a sourced OpenFOAM environment (\`WM_PROJECT_DIR\` set). On Windows use
WSL or the OpenFOAM.com Docker image. See docs/openfoam-engine.md.

The local backend runs these steps for you and streams the solver log + the
sampled velocity/temperature field back to the web viewer.
`
}
